version: "3.7"

services:
  server: # app
    image: p2p_dev:latest
    container_name: server
    volumes:
      - type: bind
        source: ./src
        target: /app/src
    ports:
      - 3001:3001
    environment:
      - "PORT=3001"
