FROM node:14.12.0

WORKDIR /app

# js and json file
COPY ./*.js* /app/
# copy .lock file
COPY ./*.lock /app/
# Install modules
RUN yarn

# Copy and compile files
COPY src ./src
COPY prisma ./prisma
# Run migration
RUN npx prisma generate
CMD [ "yarn", "dev" ]
