version: "3.7"

services:
  video_dev: # app
    image: video_dev:latest
    container_name: video_dev
    volumes:
      - type: bind
        source: ./src
        target: /app/src
    ports:
      - 3000:3000
    # environment:
    #   - "PORT=3000"
